name: Development

on: [push]

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu
        
        ruby:
          - 2.6
          - 2.7
    
    runs-on: ${{matrix.os}}-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby}}
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{runner.os}}-${{matrix.ruby}}-${{hashFiles('**/Gemfile.lock')}}
        restore-keys: |
          ${{runner.os}}-${{matrix.ruby}}-
    - name: Bundle install
      run: |
        sudo apt-get install pkg-config
        gem install bundler:2.1.4
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Run tests
      run: |
        git config --global user.email "samuel@oriontransfer.net"
        git config --global user.name "Samuel Williams"
        bundle exec bake test
